seed: 2345
dataset: 'iwslt'
context_len: 64
graph_type: 'stt'
graph_attrs:
    step: 4
    clip_dist: 3

n_layers: 6
m_layers: 6
dim_embed: 512
dim_model: 512
dim_ff: 2048
num_heads: 8
dropouti: 0.1
dropouth: 0.1
dropouta: 0.1
dropoutc: 0.1
rel_pos: True

n_epochs: 30
lr: 1.e-3
grad_accum: 1
factor: 1
batch_size: 32
dev_batch_size: 64
test_batch_size: 32
log_interval: 100
doc_max_len: 512
sent_max_len: 64
warmup: 8000

save_name: 'iwslt-4-64'
